apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domain-migration-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/domain-migration-scripts
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: domain-migration
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true