apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - bulk-pack-consumer.yaml
  - images-api.yaml
  - messaging-api.yaml
  - treetracker-admin-api.yaml
  - treetracker-contract-api.yaml
  - treetracker-earnings-api.yaml
  - treetracker-field-data.yaml
  - treetracker-grower-account-query.yaml
  - treetracker-regions-api.yaml
  - treetracker-reporting.yaml