apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/treetracker-messaging-api
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
