apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: treetracker-contract-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/treetracker-contract-api
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: treetracker-contract-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
