apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: treetracker-denormalization-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/treetracker-denormalization
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: denormalization
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
