apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: treetracker-regions-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/treetracker-regions-api
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: regions-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
