apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webmap-query-service-consumer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/webmap-query-service-consumer
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: webmap
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
