apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBKX1Qk+kPnRBf1S4AHvMdXDHK5TuqUnXxfsAgM4hg5bCiaMKxjwQ/OZhcXBouQlqS5SAhbXllnHDb57JItEl2tvjbk1HHQJSzdbbUKWU9IeHrEqjPNHLRK+tKdCEL3eIgP/dKW/H9qdIvHPKBMO/+XmfYXW4rfD5bzzv4wyygwJDxNcVdr/U78Lfu5aDx59/MI0SCJElx2TvroloarpPmr2iF/YtNZ8leJw2iE97aGyjcBMaKOOeLEBdTnkl1iVmY/nyIq2Kpskx56wwRX4v6UZqgNIF63JcdNeflyDhDclw2XMXPRE7rnD+jWFmF3qL5d0DODjc094kn74vQwEhzlKzvmacA9N3A7ef4ayqlVq0iY14oukbJaNPP20I9fL4LnOnQAGJBZni5DpdIrsvrNVNE1JlSk6nSllHZvPc2aTq4/qiQ2bNaWqCennor5QyhGfZFkcFvkbhruM9930A5+Fjcr1ceI6JHZuWuCJ9MvBZPNC9OxA3ITM0mHhiubBE+Ii8Bu+CiJlSWY78tLrItfiKD/SsoQ0yGijw6PdxQAwmJlMMAWGzptPM5jaUex4BRlX5EmaftaIjQVMoY5gjcXuTwPRnOmNDUBwWIvkioxZPyCvIQXZL0EaNNBwEZuz0QwwN/rOHonKeSSkKN+27O6eZLFa0+RHUR+sR5r6vo5j+Oa9YAtPmN1/Cm04GA4UhXFtsUZVJPM4dHCI70fMsrP9bcqBt1e5fcWEjWVHvvNnXCydou7PQtDhhsMdEb5tH8wAzr6FUwKqQ==