apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-poc-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greenstand/argo-cd-poc-app
    targetRevision: HEAD
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd-poc-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
