apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.2/manifests/ha/install.yaml
  - resources/argocd-mapping.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --insecure
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --rootpath=/argocd
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --basehref=/argocd
    target:
      kind: Deployment
      name: argocd-server

patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/argocd-notifications-cm.yaml