apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
  - resources/argocd-mapping.yaml

patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/argocd-notifications-cm.yaml
  - overlays/argocd-server.yaml