apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgALoyPQn5AP4wTeYRmF2sGlixtYum4H4CIw0SV6j7pLIQ0Jkx4xoQq+KaIpwzKsZVeTdiUuaHi6H/SiyrityxegwzSFiIAMqyr7JO1ncNocZTQINLEHEOlnJZV5qlxuKKSOGNWWr9h0GSwYXuxFCEL9SZcuSOG2F7JpiqDH9RFT3cai+6EowUIvxXxSS2+pRaWBXpr2nBiFlabdJZSEm1/YVuDjGHKHp5pxZpTEUW6Hg6jOelPM4KMf/+VQiVlTpKNe/Mj/VO3TN6MzLRCZHBilYg9lawemLDVwyYH45Z+sjfaSkbDItIU0pbC0u8w3RcCwbejSNETFQzfPM8/W9l87bI98N5/ss+q32OzYq2yDaEk56kn+H4X8nl2dtKh/DJ4zJjZ0uG1ijntHbFI0CDFtwyyZdb73HmTRLLKXkz07CDAS0Gz4LKKAX5Q4yiP9u/egmjqtHGtgQIE07TuJdY5E52kkCfja8Ehv6zTCkNn2Khxoqa7lhAIC+Ao3R6MIePx2q/NxZHomTqT5vv8uZOM8hUa0f3Z0hDyG52rs4amqlQ5HBhpKlrcIrHgKYe7QIlCajdPni8lWq70PU3315AiFlIPcewJiDv9YOeZzXTNkVoTcFmoT6kubqDhnmBEsCTkn3JeLd509PmdVguy5v32MSfT1XaWBx3cKSynyjscOCBqR5xJ22zIOhcYWRDeRuV/dutOSU5Fo/MEsX5hHjajDZ1l1A6xWkl2AL+Za6+kKF+FS9ghtjmjrixfbz+Akj6PaCMfXzO50NA==